package ro.cs.pub.pubsub.tera.neighbor;

import ro.cs.pub.pubsub.message.MessageContent;

public class NeighborMessage implements MessageContent {
	private static final long serialVersionUID = 1L;

	/**
	 * View generated by the sending agent.
	 */
	private final View view;

	/**
	 * The type of message.
	 */
	private final boolean reply;

	public NeighborMessage(View view, boolean reply) {
		this.view = view;
		this.reply = reply;
	}

	public View getView() {
		return view;
	}

	public boolean isReply() {
		return reply;
	}

	@Override
	public String toString() {
		return "NeighborMessage [reply=" + reply + ", view=" + view + "]";
	}
}
