package ro.cs.pub.pubsub.tera.behaviour.neighbor.message;

import ro.cs.pub.pubsub.message.MessageContent;
import ro.cs.pub.pubsub.tera.behaviour.neighbor.View;

public class ShufflingMessage implements MessageContent {
	private static final long serialVersionUID = 1L;

	/**
	 * View generated by the sending agent.
	 */
	private final View view;

	public ShufflingMessage(View view) {
		this.view = view;
	}

	public View getView() {
		return view;
	}

	@Override
	public String toString() {
		return "ShufflingMessage [view=" + view + "]";
	}
}
